/*LLENAR TABLA DE MARCA*/
use tallerbd;
insert into marca values (null, 'ABARTH');
insert into marca values (null, 'ACURA');
insert into marca values (null, 'ALFA ROMEO');
insert into marca values (null, 'ALPINE');
insert into marca values (null, 'AMERICAN MOTORS');
insert into marca values (null, 'ASIA MOTORS');
insert into marca values (null, 'ASTON MARTIN');
insert into marca values (null, 'AUDI');
insert into marca values (null, 'AUSTIN-HEALEY');
insert into marca values (null, 'BENTLEY');
insert into marca values (null, 'BMW');
insert into marca values (null, 'BUGATTI');
insert into marca values (null, 'BUICK');
insert into marca values (null, 'BYD');
insert into marca values (null, 'CADILLAC');
insert into marca values (null, 'CHERY');
insert into marca values (null, 'CHEVROLET');
insert into marca values (null, 'CHRYSLER');
insert into marca values (null, 'CITROEN');
insert into marca values (null, 'DACIA');
insert into marca values (null, 'DAEWOO');
insert into marca values (null, 'DE TOMASO');
insert into marca values (null, 'DELOREAN');
insert into marca values (null, 'DEVON MOTORWORKS');
insert into marca values (null, 'DFSK');
insert into marca values (null, 'DODGE');
insert into marca values (null, 'DS');
insert into marca values (null, 'FERRARI');
insert into marca values (null, 'FIAT');
insert into marca values (null, 'FORD');
insert into marca values (null, 'GMC');
insert into marca values (null, 'GUMPERT');
insert into marca values (null, 'HONDA');
insert into marca values (null, 'HUMMER');
insert into marca values (null, 'HYUNDAI');
insert into marca values (null, 'INFINITI');
insert into marca values (null, 'INVICTA');
insert into marca values (null, 'ISUZU');
insert into marca values (null, 'JAGUAR');
insert into marca values (null, 'JEEP');
insert into marca values (null, 'KIA');
insert into marca values (null, 'KOENIGSEGG');
insert into marca values (null, 'LADA');
insert into marca values (null, 'LAMBORGHINI');
insert into marca values (null, 'LANCIA');
insert into marca values (null, 'LAND ROVER');
insert into marca values (null, 'LEXUS');
insert into marca values (null, 'LINCOLN');
insert into marca values (null, 'LOTUS');
insert into marca values (null, 'MAHINDRA');
insert into marca values (null, 'MARCOS');
insert into marca values (null, 'MASERATI');
insert into marca values (null, 'MAYBACH');
insert into marca values (null, 'MAZDA');
insert into marca values (null, 'MCLAREN');
insert into marca values (null, 'MERCEDES BENZ');
insert into marca values (null, 'MERCURY');
insert into marca values (null, 'MINI');
insert into marca values (null, 'MITSUBISHI');
insert into marca values (null, 'MORGAN');
insert into marca values (null, 'MORRIS MOTORS');
insert into marca values (null, 'NISSAN');
insert into marca values (null, 'OLDSMOBILE');
insert into marca values (null, 'OPEL');
insert into marca values (null, 'PAGANI');
insert into marca values (null, 'PEUGEOT');
insert into marca values (null, 'PLYMOUTH');
insert into marca values (null, 'PONTIAC');
insert into marca values (null, 'PORSCHE');
insert into marca values (null, 'RENAULT');
insert into marca values (null, 'ROLLS-ROYCE');
insert into marca values (null, 'ROVER');
insert into marca values (null, 'SALEEN');
insert into marca values (null, 'SATURN');
insert into marca values (null, 'SEAT');
insert into marca values (null, 'SHELBY');
insert into marca values (null, 'SKODA');
insert into marca values (null, 'SMART');
insert into marca values (null, 'SPYKER CARS');
insert into marca values (null, 'SSANGYONG');
insert into marca values (null, 'SUBARU');
insert into marca values (null, 'SUZUKI');
insert into marca values (null, 'TATA');
insert into marca values (null, 'TESLA');
insert into marca values (null, 'TOYOTA');
insert into marca values (null, 'VOLKSWAGEN VW');
insert into marca values (null, 'VOLVO');
insert into marca values (null, 'W MOTORS');


select *from marca;